# Generated by Django 3.2.7 on 2021-09-17 15:25

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Adventure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startingmessage',
            options={'verbose_name': 'Starting Message', 'verbose_name_plural': 'Starting Messages'},
        ),
        migrations.RenameField(
            model_name='startingmessage',
            old_name='Adventure',
            new_name='adventure',
        ),
        migrations.RemoveField(
            model_name='startingmessage',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='adventure',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='startingmessage',
            name='message_text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='adventure',
            constraint=models.UniqueConstraint(fields=('name',), name='adventure_name_constraint'),
        ),
        migrations.AddConstraint(
            model_name='startingmessage',
            constraint=models.UniqueConstraint(fields=('adventure',), name='message_adventure_constraint'),
        ),
    ]
