# Generated by Django 3.2.7 on 2021-09-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='answer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adventure',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
