# Generated by Django 3.2.7 on 2021-09-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adventure', '0002_auto_20210917_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiofile', models.FileField(upload_to='configuration')),
            ],
        ),
        migrations.AddConstraint(
            model_name='audio',
            constraint=models.UniqueConstraint(fields=('audiofile',), name='audiofile_unique_constraint'),
        ),
    ]
