# Generated by Django 3.2.7 on 2021-09-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adventure', '0002_auto_20210923_1634'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clue',
            name='clue_adventure_constraint',
        ),
        migrations.AddConstraint(
            model_name='clue',
            constraint=models.UniqueConstraint(fields=('adventure', 'clueorder'), name='clue_adventure_constraint'),
        ),
    ]
