# Generated by Django 3.2.7 on 2021-09-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adventure', '0003_auto_20210917_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='startingmessage',
            name='audio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='audio', to='Adventure.audio'),
            preserve_default=False,
        ),
    ]
