# Generated by Django 3.2.7 on 2021-09-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adventure', '0004_startingmessage_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audiofile',
            field=models.FileField(upload_to='audio_files'),
        ),
    ]
