# Generated by Django 3.2.7 on 2021-09-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adventure', '0007_auto_20210917_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MessageDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Message Type',
                'verbose_name_plural': 'Message Types',
            },
        ),
        migrations.AddConstraint(
            model_name='messagedisplay',
            constraint=models.UniqueConstraint(fields=('name',), name='message_type_constraint'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('image',), name='imagefile_unique_constraint'),
        ),
        migrations.AddField(
            model_name='startingmessage',
            name='display',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='display', to='Adventure.messagedisplay'),
            preserve_default=False,
        ),
    ]
