# Generated by Django 3.2.7 on 2021-09-17 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adventure', '0008_auto_20210917_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startingmessage',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='audio', to='Adventure.audio'),
        ),
    ]
