# Generated by Django 3.2.7 on 2021-09-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adventure', '0009_alter_startingmessage_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clueorder', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth'), (9, 'Ninth'), (10, 'Tenth'), (11, 'Eleventh'), (12, 'Twelfth'), (13, 'Thirteenth'), (14, 'Fourteenth'), (15, 'Fifteenth')])),
            ],
            options={
                'verbose_name': 'Starting Message',
                'verbose_name_plural': 'Starting Messages',
            },
        ),
        migrations.CreateModel(
            name='ClueDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Clue Type',
                'verbose_name_plural': 'Clue Types',
            },
        ),
        migrations.AddConstraint(
            model_name='cluedisplay',
            constraint=models.UniqueConstraint(fields=('name',), name='clue_type_constraint'),
        ),
        migrations.AddField(
            model_name='clue',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='adventure', to='Adventure.adventure'),
        ),
        migrations.AddField(
            model_name='clue',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='audio', to='Adventure.audio'),
        ),
        migrations.AddField(
            model_name='clue',
            name='display',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='display', to='Adventure.messagedisplay'),
        ),
        migrations.AddConstraint(
            model_name='clue',
            constraint=models.UniqueConstraint(fields=('adventure',), name='clue_adventure_constraint'),
        ),
    ]
