# Generated by Django 3.2.7 on 2021-09-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adventure', '0010_auto_20210917_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clue',
            options={},
        ),
        migrations.AddField(
            model_name='clue',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
